name: US Constitution Bot
on:
  push:
    branches:
      - 'master'
env:
  TG_TOKEN: ${{ secrets.TOKEN }}
  ADMIN_ID: ${{ secrets.ADMIN_ID }}
  BOT_ID: ${{ secrets.BOT_ID }}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5.2.0
      with:
        python-version: 3.11.4
    - run: python app.py
