name: US Constitution Bot
on:
  push:
    branches:
      - 'prod'
env:
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  ADMIN_ID: ${{ secrets.ADMIN_ID }}
  BOT_ID: ${{ secrets.BOT_ID }}
  WHITELIST_IDS: ${{ secrets.WHITELIST_IDS }}
jobs:
  deploy:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: Checkout latest
      uses: actions/checkout@v4
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
    - name: Setup Python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: 3.11.4
        cache: pip
    - run: pip install -r requirements.txt && python app.py --no-whitelist --no-login
